version: '3.8'

services:
  backend:
    build:
      context: .
    container_name: parser_back
    restart: always
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:2104@db/parser
    depends_on:
      - db

  frontend:
    build:
      context: ../practica_front
    container_name: parser_front
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend

  db:
    image: postgres:13
    container_name: parser_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 2104
      POSTGRES_DB: parser
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
